sudo: required
dist: trusty
before_install:
    - sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended latexmk texlive-lang-german texlive-doc-de pgf texlive-font-utils zip inkscape
      

script:
    - mkdir output
    - cd Blatt01
    - latexmk -pdf main.tex
    - mv main.pdf ../output/Blatt01.pdf
    - cd ..
    - zip -j output/Blatt01.zip output/Blatt01.pdf Blatt01/b01a01.m
    - cd Blatt02
    - latexmk -pdf main.tex
    - mv main.pdf ../output/Blatt02.pdf
    - cd ..
    - zip -j output/Blatt02.zip output/Blatt02.pdf
    - cd Blatt03
    - latexmk -pdf main.tex
    - mv main.pdf ../output/Blatt03.pdf
    - cd ..
    - zip -j output/Blatt03.zip output/Blatt03.pdf
    - cd Blatt04
    - latexmk -pdf main.tex
    - mv main.pdf ../output/Blatt04.pdf
    - cd ..
    - zip -j output/Blatt04.zip output/Blatt04.pdf Blatt04/b04a02.m
    - cd Blatt05
    - latexmk -pdf --shell-escape main.tex
    - mv main.pdf ../output/Blatt05.pdf
    - cd ..
    - zip -j output/Blatt05.zip output/Blatt05.pdf Blatt05/b05a02.m Blatt05/initWeights.m Blatt05/train.m Blatt05/forward.m Blatt05/propagateError.m Blatt05/transDiff.m
    - cd Blatt06
    - latexmk -pdf main.tex
    - mv main.pdf ../output/Blatt06.pdf
    - cd ..
    - zip -j output/Blatt06.zip output/Blatt06.pdf Blatt06/b06a01.m Blatt06/C.m
    - cd Blatt07
    - latexmk -pdf main.tex
    - mv main.pdf ../output/Blatt07.pdf
    - cd ..
    - zip -j output/Blatt07.zip output/Blatt07.pdf Blatt07/b07a02.m Blatt07/trainNetworks.m
    - cd Blatt08
    - latexmk -pdf main.tex
    - mv main.pdf ../output/Blatt08.pdf
    - cd ..
    - zip -j output/Blatt08.zip output/Blatt08.pdf Blatt08/b08a02.m Blatt08/networkRegression.m
    - cd Blatt09
    - latexmk -pdf main.tex
    - mv main.pdf ../output/Blatt09.pdf
    - cd ..
    - zip -j output/Blatt09.zip output/Blatt09.pdf 
    
deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
    keep-history: true
    local-dir: output
    on:
        branch: master
